### ISSUE TITLE
Välipalautus 2 vertaisarviointi

### ISSUE THREAD

**Issue by limi96** [shlevanto/Tsoha-s2021#1]
Sovelluksen ulkoasu on toteutettu erinomaisesti ja sovellusta on myös helppo käyttää. Sovelluksessa on hyvin huomioitu todella paljon eri yksityiskohtia esimerkiksi käyttäjän syötteiden rajoittaminen. 

Sovelluksen koodin rakenne on todella johdonmukainen ja erittäin selkeä. Selvästi pylint-pisteet ovat korkealla! Tietokanta on toteutettu todella hyvin ja SQL-kyselyt ovat toimivia.

Tapahtumat-sivun toiminnot näyttävät olevan keskeneräisiä. Kaikki kirjaustapahtumat palauttavat "Internal server error". Näihin kenttiin olisi myös hyvä laittaa tekstinä, että minkälaisessa muodossa odotetaan syötteiden olevan. Esim. Päivämäärissä DD/MM/YYYY jne.

**Comment by shlevanto** [comment]
Kitos palautteesta.
