### ISSUE TITLE
Vertaisarvio 2

### ISSUE THREAD

**Issue by aapohu** [shlevanto/Tsoha-s2021#2]
Tapahtumia kirjatessa tulee server error oletettavasti päivämäärästä. Koodia tutkimalla löytyy että haluttu formaatti on 2021-10-13T23:10. Kun päivämäärän antaa tarkalleen oikein niin toiminnot toimivat kuten pitääkin. Käyttöliittymä on muuten selkeä ja helppokäyttöinen. 

Koodi on selkeää ja tarkasti dokumentoitua.
Tietokanta on toteutettu järkevästi.

Kaiken kaikkiaan sovellus on oikein hyvällä mallilla.

**Comment by shlevanto** [comment]
Kiitos huomioista. Server error tulee näköjään ainakin jos päivämäärä on tyhjä. Täytyy lisätä siihen validointi.
